### ISSUE TITLE
Maybe a bug?

### ISSUE THREAD

**Issue by OldGodShen** [TeamMoegMC/FrostedHeart#13]
无法在Loliserver中加载

-- Head --
Thread: main
Stacktrace:
        at com.teammoeg.frostedheart.world.FHOreFeatureConfig$FillerBlockType.<clinit>(FHOreFeatureConfig.java:53) ~[frostedheart:1.16.5-0.4.7-stable2.2] {re:classloading}
-- MOD frostedheart --
Details:
        Mod File: frostedheart-1.16.5-0.4.7-stable2.2-hf1.jar
        Failure message: TWR Frosted Heart (frostedheart) encountered an error during the load_registries event phase
                java.lang.NoSuchFieldError: TUFA_LIMESTONE
        Mod Version: 1.16.5-0.4.7-stable2.2
        Mod Issue URL: https://github.com/TeamMoegMC/FrostedHeart/issues
        Exception message: java.lang.NoSuchFieldError: TUFA_LIMESTONE
Stacktrace:
        at com.teammoeg.frostedheart.world.FHOreFeatureConfig$FillerBlockType.<clinit>(FHOreFeatureConfig.java:53) ~[frostedheart:1.16.5-0.4.7-stable2.2] {re:classloading}
        at com.teammoeg.frostedheart.world.FHFeatures.<clinit>(FHFeatures.java:40) ~[frostedheart:1.16.5-0.4.7-stable2.2] {re:classloading}
        at com.teammoeg.frostedheart.events.RegistryEvents.onFeatureRegistry(RegistryEvents.java:108) ~[frostedheart:1.16.5-0.4.7-stable2.2] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_335_RegistryEvents_onFeatureRegistry_Register.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:121) ~[forge:36.2] {re:classloading}
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?] {}
        at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:246) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:233) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:199) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:121) ~[?:?] {re:classloading,re:mixin,pl:mixin:A}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[LoliServer-1.16.5-c3507dc-server.jar:36.2] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:86) [LoliServer-1.16.5-c3507dc-server.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:83) [LoliServer-1.16.5-c3507dc-server.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:80) [LoliServer-1.16.5-c3507dc-server.jar:?] {}

-- System Details --
Details:
        Minecraft Version: 1.16.5
        Minecraft Version ID: 1.16.5
        LoliServer Version: 1.16.5-c3507dc
        Operating System: Windows 11 (amd64) version 10.0
        Java Version: 11.0.14.1, Azul Systems, Inc.
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Azul Systems, Inc.
        Memory: 790077160 bytes (753 MB) / 1330642944 bytes (1269 MB) up to 4217372672 bytes (4022 MB)
        CPUs: 8
        JVM Flags: 0 total;
        ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
        ModLauncher launch target: fmlserver
        ModLauncher naming: srg
        ModLauncher services:
                /mixin-0.8.4.jar mixin PLUGINSERVICE
                /eventbus-4.0.0.jar eventbus PLUGINSERVICE
                /LoliServer-1.16.5-c3507dc-server.jar object_holder_definalize PLUGINSERVICE
                /LoliServer-1.16.5-c3507dc-server.jar runtime_enum_extender PLUGINSERVICE
                /LoliServer-1.16.5-c3507dc-server.jar capability_inject_definalize PLUGINSERVICE
                /accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE
                /LoliServer-1.16.5-c3507dc-server.jar runtimedistcleaner PLUGINSERVICE
                /mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE
                /LoliServer-1.16.5-c3507dc-server.jar fml TRANSFORMATIONSERVICE
        FML: 36.2
        Forge: net.minecraftforge:36.2.34
        FML Language Providers:
                javafml@36.2
                minecraft@1
                kotlinforforge@1.16.0
        Mod List:
                ClientTweaks_1.16.3-5.3.0.jar                     |Client Tweaks                 |clienttweaks
        |5.3.0               |COMMON_SET|Manifest: NOSIGNATURE
                rhino-forge-1605.1.5-build.75.jar                 |Rhino                         |rhino
        |1605.1.5-build.75   |COMMON_SET|Manifest: NOSIGNATURE
                Cucumber-1.16.5-4.1.12.jar                        |Cucumber Library              |cucumber
        |4.1.12              |COMMON_SET|Manifest: NOSIGNATURE
                CustomSkinLoader_ForgeLegacy-14.14-SNAPSHOT-323.ja|CustomSkinLoader              |customskinloader              |14.14-SNAPSHOT-323  |COMMON_SET|Manifest: 4a:31:8b:cf:34:eb:d0:13:f3:19:39:d5:d2:b9:12:78:b5:f2:8d:91:3e:6f:8f:ed:97:48:00:69:e1:30:3a:54
                jei-1.16.5-7.7.1.152.jar                          |Just Enough Items             |jei
        |7.7.1.152           |COMMON_SET|Manifest: NOSIGNATURE
                ExtendedCrafting-1.16.5-3.1.11.jar                |Extended Crafting             |extendedcrafting              |3.1.11              |COMMON_SET|Manifest: NOSIGNATURE
                BetterCaves-Forge-1.16.4-1.1.2.jar                |YUNG's Better Caves           |bettercaves
        |1.16.4-1.1.2        |COMMON_SET|Manifest: NOSIGNATURE
                PassableFoliage-1.16.5-2.4.0.jar                  |Passable Foliage              |passablefoliage               |2.4.0               |COMMON_SET|Manifest: NOSIGNATURE
                mgui-1.16.5-3.3.0.jar                             |mgui                          |mgui
        |3.3.0               |COMMON_SET|Manifest: NOSIGNATURE
                comforts-forge-1.16.5-4.0.1.5.jar                 |Comforts                      |comforts
        |1.16.5-4.0.1.5      |COMMON_SET|Manifest: NOSIGNATURE
                YungsApi-1.16.4-Forge-13.jar                      |YUNG's API                    |yungsapi
        |1.16.4-Forge-13     |COMMON_SET|Manifest: NOSIGNATURE
                stoneholm-1.2.2.jar                               |Stoneholm                     |stoneholm
        |1.2                 |COMMON_SET|Manifest: NOSIGNATURE
                Bookshelf-Forge-1.16.5-10.4.32.jar                |Bookshelf                     |bookshelf
        |10.4.32             |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
                CrockPot-1.16.5-2.1.0-release.jar                 |Crock Pot                     |crockpot
        |2.1.0-release       |COMMON_SET|Manifest: NOSIGNATURE
                Morpheus-1.16.5-4.2.70.jar                        |Morpheus                      |morpheus
        |4.2.70              |COMMON_SET|Manifest: NOSIGNATURE
                IronAgeFurniture-1.16.3-1.16.5-0.2.0.15.jar       |Iron Age Furniture            |ironagefurniture              |1.16.5-0.2.0.15     |COMMON_SET|Manifest: NOSIGNATURE
                worldshape-1.0.jar                                |Worldshape                    |worldshape
        |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
                stone-age-1.16.5-1.4.3.jar                        |TWR Stone Age                 |stone_age
        |1.16.5-1.4.3        |COMMON_SET|Manifest: NOSIGNATURE
                SnowRealMagic-1.16.4-2.9.0.jar                    |Snow! Real Magic!             |snowrealmagic
        |2.9.0               |COMMON_SET|Manifest: NOSIGNATURE
                Kiwi-1.16.5-3.6.1.jar                             |Kiwi                          |kiwi
        |3.6.1               |COMMON_SET|Manifest: NOSIGNATURE
                cameraoverhaul-1.0-1.16.4.jar                     |Camera Overhaul               |cameraoverhaul                |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
                ImmersivePetroleum-1.16.5-3.3.0-9.jar             |Immersive Petroleum           |immersivepetroleum            |3.3.0-9             |COMMON_SET|Manifest: NOSIGNATURE
                frozenup-1.0.1.jar                                |Frozen Up                     |frozenup
        |1.0.1               |COMMON_SET|Manifest: NOSIGNATURE
                forge-1.16.5-36.2.34-universal.jar                |Forge                         |forge
        |36.2.34             |COMMON_SET|Manifest: NOSIGNATURE
                charcoal_pit-1.16.5-2.29.jar                      |Charcoal Pit                  |charcoal_pit
        |2.23b               |COMMON_SET|Manifest: NOSIGNATURE
                ironchest-1.16.5-11.2.21.jar                      |Iron Chests                   |ironchest
        |1.16.5-11.2.21      |COMMON_SET|Manifest: NOSIGNATURE
                corpse-1.16.5-1.0.6.jar                           |Corpse                        |corpse
        |1.16.5-1.0.6        |COMMON_SET|Manifest: NOSIGNATURE
                weatherforecast-1.0.4.jar                         |Weather Forecast              |weatherforecast               |1.0.4               |COMMON_SET|Manifest: NOSIGNATURE
                forge-1.16.5-36.2.34-server.jar                   |Minecraft                     |minecraft
        |1.16.5              |COMMON_SET|Manifest: NOSIGNATURE
                EnchantmentDescriptions-1.16.5-7.0.19.jar         |EnchantmentDescriptions       |enchdesc
        |7.0.19              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
                theoneprobe-1.16-3.1.7.jar                        |The One Probe                 |theoneprobe
        |1.16-3.1.7          |COMMON_SET|Manifest: NOSIGNATURE
                towers_of_the_wild-1.16.3-2.1.0.1.jar             |Towers Of The Wild            |towers_of_the_wild            |1.16.3-2.1.0        |COMMON_SET|Manifest: NOSIGNATURE
                smoothboot-forge-1.16.4-1.2.2.jar                 |Smooth Boot                   |smoothboot
        |1.16.4-1.2.2        |COMMON_SET|Manifest: NOSIGNATURE
                spark-forge.jar                                   |spark                         |spark
        |1.6.0               |COMMON_SET|Manifest: NOSIGNATURE
                flywheel-1.16-0.2.5.jar                           |Flywheel                      |flywheel
        |1.16-0.2.5          |COMMON_SET|Manifest: NOSIGNATURE
                steampowered-1.16.5-1.1.14.jar                    |Create: Steam Powered         |steampowered
        |1.16.5-1.1.14       |COMMON_SET|Manifest: NOSIGNATURE
                create-mc1.16.5_v0.3.2g.jar                       |Create                        |create
        |v0.3.2g             |COMMON_SET|Manifest: NOSIGNATURE
                curios-forge-1.16.5-4.0.8.2.jar                   |Curios API                    |curios
        |1.16.5-4.0.8.2      |COMMON_SET|Manifest: NOSIGNATURE
                tetra-1.16.5-3.20.0.jar                           |Tetra                         |tetra
        |3.20.0              |COMMON_SET|Manifest: NOSIGNATURE
                tetrapak-1.16.5-0.3.4.jar                         |Tetra Pak                     |tetrapak
        |1.16.5-0.3.4        |COMMON_SET|Manifest: NOSIGNATURE
                Patchouli-1.16.4-53.2.jar                         |Patchouli                     |patchouli
        |1.16.4-53.2         |COMMON_SET|Manifest: NOSIGNATURE
                ftb-backups-2.1.2.2.jar                           |FTB Backups                   |ftbbackups
        |2.1.2.2             |COMMON_SET|Manifest: NOSIGNATURE
                diet-forge-1.16.5-1.0.4.0.jar                     |Diet                          |diet
        |1.16.5-1.0.4.0      |COMMON_SET|Manifest: NOSIGNATURE
                StrongerSnowballs-1.16.5-5.0.2.jar                |StrongerSnowballs             |strongersnowballs             |5.0.2               |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
                StorageDrawers-1.16.3-8.5.1.jar                   |Storage Drawers               |storagedrawers                |8.5.1               |COMMON_SET|Manifest: NOSIGNATURE
                YungsExtras-Forge-1.16.4-1.0.jar                  |YUNG's Extras                 |yungsextras
        |Forge-1.16.4-1.0    |COMMON_SET|Manifest: NOSIGNATURE
                ages-api-1.16.5-1.2.0.jar                         |Ages API                      |ages_api
        |1.16.5-1.2.0        |COMMON_SET|Manifest: NOSIGNATURE
                elevatorid-1.16.5-1.7.13.jar                      |Elevator Mod                  |elevatorid
        |1.16.5-1.7.13       |COMMON_SET|Manifest: NOSIGNATURE
                BetterStrongholds-1.16.4-1.2.1.jar                |YUNG's Better Strongholds     |betterstrongholds             |1.16.4-1.2.1        |COMMON_SET|Manifest: NOSIGNATURE
                cfm-7.0.0pre22-1.16.3.jar                         |MrCrayfish's Furniture Mod    |cfm
        |7.0.0-pre22         |COMMON_SET|Manifest: NOSIGNATURE
                architectury-1.24.35-forge.jar                    |Architectury                  |architectury
        |1.24.35             |COMMON_SET|Manifest: NOSIGNATURE
                ftb-library-forge-1605.3.4-build.90.jar           |FTB Library                   |ftblibrary
        |1605.3.4-build.90   |COMMON_SET|Manifest: NOSIGNATURE
                item-filters-forge-1605.2.5-build.9.jar           |Item Filters                  |itemfilters
        |1605.2.5-build.9    |COMMON_SET|Manifest: NOSIGNATURE
                ftb-teams-forge-1605.2.3-build.40.jar             |FTB Teams                     |ftbteams
        |1605.2.3-build.40   |COMMON_SET|Manifest: NOSIGNATURE
                ftb-chunks-forge-1605.3.2-build.81.jar            |FTB Chunks                    |ftbchunks
        |1605.3.2-build.81   |COMMON_SET|Manifest: NOSIGNATURE
                kubejs-forge-1605.3.19-build.299.jar              |KubeJS                        |kubejs
        |1605.3.19-build.299 |COMMON_SET|Manifest: NOSIGNATURE
                ftb-quests-forge-1605.3.6-build.98.jar            |FTB Quests                    |ftbquests
        |1605.3.6-build.98   |COMMON_SET|Manifest: NOSIGNATURE
                ftb-ranks-forge-1605.1.5-build.16.jar             |FTB Ranks                     |ftbranks
        |1605.1.5-build.16   |COMMON_SET|Manifest: NOSIGNATURE
                kubejs-create-1605.1.4-build.12.jar               |KubeJS Create                 |kubejs_create
        |1605.1.4-build.12   |COMMON_SET|Manifest: NOSIGNATURE
                ferritecore-2.1.0-forge.jar                       |Ferrite Core                  |ferritecore
        |2.1.0               |COMMON_SET|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
                engineersdecor-1.16.5-1.1.17.jar                  |Engineer's Decor              |engineersdecor                |1.1.17              |COMMON_SET|Manifest: bf:30:76:97:e4:58:41:61:2a:f4:30:d3:8f:4c:e3:71:1d:14:c4:a1:4e:85:36:e3:1d:aa:2f:cb:22:b0:04:9b
                cloth-config-4.12.41-forge.jar                    |Cloth Config v4 API           |cloth-config
        |4.12.41             |COMMON_SET|Manifest: NOSIGNATURE
                modular-routers-1.16.5-7.5.2-83.jar               |Modular Routers               |modularrouters                |task ':jar' property|COMMON_SET|Manifest: NOSIGNATURE
                rankine-1.16.5-1.3.1-hotfix1.jar                  |Project Rankine               |rankine
        |1.3.1               |COMMON_SET|Manifest: NOSIGNATURE
                frostedheart-1.16.5-0.4.7-stable2.2-hf1.jar       |TWR Frosted Heart             |frostedheart
        |1.16.5-0.4.7-stable2|VALIDATE  |Manifest: NOSIGNATURE
                primalwinter-forge-1.16.4-2.0.7.jar               |Primal Winter                 |primalwinter
        |2.0.7               |COMMON_SET|Manifest: NOSIGNATURE
                ImmersiveEngineering-1.16.5-5.0.7-143.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-5.0.7-143    |COMMON_SET|Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
                ImmersiveIndustry-1.16.5-0.1.6d.jar               |Immersive Industry            |immersiveindustry             |1.16.5-0.1.6d       |COMMON_SET|Manifest: NOSIGNATURE
                WaterSource-1.1.40-release-1.16.5.jar             |Water Source                  |watersource
        |1.1.40-release-1.16.|COMMON_SET|Manifest: NOSIGNATURE
                kubejs-immersive-engineering-1605.1.2-build.28.jar|KubeJS Immersive Engineering  |kubejs_immersive_engineering  |1605.1.2-build.28   |COMMON_SET|Manifest: NOSIGNATURE
                BetterMineshafts-Forge-1.16.4-2.0.4.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.4        |COMMON_SET|Manifest: NOSIGNATURE
                BetterAdvancements-1.16.5-0.1.1.115.jar           |Better Advancements           |betteradvancements            |0.1.1.115           |COMMON_SET|Manifest: NOSIGNATURE
        Crash Report UUID: 9223277d-4ced-4cbd-b7d9-3afff689c1d7
        Kiwi Modules:
                kiwi:contributors
                kiwi:data
                snowrealmagic:core
                snowrealmagic:world
        CraftBukkit Information:
   Running:
   Failed to handle CraftCrashReport: craftbukkit not runs
[08:05:35][main][FATAL]: Failed to start the minecraft server

**Comment by khjxiaogu** [comment]
As seen on curseforge page:
![X}FV84 HUG58TB 3 GAI9](https://user-images.githubusercontent.com/54445543/173607671-1ebab0a7-aee7-4ccb-a5f2-7d4adcb6f6cc.png)
